#ifndef DEFINE_H_
#define DEFINE_H_ "DEFINE_H_"

#include "rsdl.hpp"
#include <vector>
#include <fstream>
#include <sstream>
#include <algorithm>
#include <string>
#include <chrono>
#define PI 3.14159265
#define MAXX 100000
#define WINDOWS_WIDTH 682.5
#define WINDOWS_HEIGHT 512
#define SQUARES_COUNT_X 18
#define SQUARES_COUNT_Y 11
#define FONT_SIZE 15
#define FONT_LOCATION "Icons/OpenSans.ttf"
#define BACKGROUND_MUSIC "SoundEffects/bgmusic.mp3"
#define FILE_EXTENSION ".png"
#define INITIAL_MONEY 200
#define INITIAL_LIFE 20
#define FSQUARE_X 60
#define FSQUARE_Y 87.5
#define LSQUARE_X 630
#define LSQUARE_Y 417.5
#define SQUARE_L 30
#define SHOT_L 10
#define SHOT_SPEED 180
#define FORMAT_LENGTH 4
#define D_TIME 0.01
#define WAVES_TIME_BREAK 3
#define ENEMY_DEPLOY_TIME 0.5
#define NEW_WAVE_ADDED_LIFE 0.1
#define NUMBER_OF_UPGRADES '3'
#define RIGHT_DIRECTION "right"
#define UP_DIRECTION "up"
#define LEFT_DIRECTION "left"
#define DOWN_DIRECTION "down"
#define END_OF_PATH "end_of_path"
#define REFUND_PERCENTAGE 0.8
#define INPUT_FILE_NAME "waves.txt"
#define APP_NAME "Fieldrunners"
#define BACK_GROUND_PNG "Icons/background.png"
#define HEART_PNG "Icons/heart.png"
#define MONEY_PNG "Icons/money.png"
#define SQUARE_PNG "Icons/square.png"
#define SELECTED_SQUARE "Icons/selectedsquare.png"
#define INITIAL_BUILD_STATUS "Initial_Build"
#define GATTLING_TOWERS "Icons/Gattling/Gattling1"
#define MISSILE_TOWERS "Icons/Missile/Missile1"
#define TESLA_TOWERS "Icons/Tesla/Tesla1"
#define GLUE_TOWERS "Icons/Glue/Glue1"
#define GATTLING_TOWER_LVL1 "Icons/Gattling/Gattling1/1.png"
#define MISSILE_TOWER_LVL1 "Icons/Missile/Missile1/1.png"
#define TESLA_TOWER_LVL1 "Icons/Tesla/Tesla1/1.png"
#define GATTLING_TOWER_LVL2 "Icons/gattling2.png"
#define MISSILE_TOWER_LVL2 "Icons/missile2.png"
#define TESLA_TOWER_LVL2 "Icons/tesla2.png"
#define GATTLING_TOWER_LVL3 "Icons/gattling3.png"
#define MISSILE_TOWER_LVL3 "Icons/missile3.png"
#define TESLA_TOWER_LVL3 "Icons/tesla3.png"
#define GLUE_TOWER_LVL1 "Icons/Glue/Glue1/1.png"
#define GLUE_TOWER_LVL2 "Icons/glue2.png"
#define GLUE_TOWER_LVL3 "Icons/glue3.png"
#define GATTLLING_TOWER_DAMAGE 35
#define GATTLING_TOWER_LOADING_TIME 1
#define GATTLING_TOWER_INITIAL_COST 55
#define GATTLING_TOWER_UPGRADE_COST 40
#define GATTLING_TOWER_UPGRADE_ADDED_DAMAGE 35
#define MISSILE_TOWER_DAMAGE 75
#define MISSILE_TOWER_LOADING_TIME 3
#define MISSILE_TOWER_INITIAL_COST 70
#define MISSILE_TOWER_UPGRADE_COST 60
#define MISSILE_TOWER_UPGRADE_ADDED_DAMAGE 75
#define MISSILE_TOWER_DAMAGE_RANGE 25
#define TESLA_TOWER_DAMAGE 700
#define TESLA_TOWER_LOADING_TIME 1.5
#define TESLA_TOWER_INITIAL_COST 120
#define TESLA_TOWER_UPGRADE_COST 100
#define TESLA_TOWER_UPGRADE_ADDED_DAMAGE 1000
#define GLUE_TOWER_DAMAGE 0.4
#define GLUE_TOWER_LOADING_TIME 2
#define GLUE_TOWER_INITIAL_COST 60
#define GLUE_TOWER_UPGRADE_COST 45
#define GLUE_TOWER_UPGRADE_ADDED_DAMAGE 0.1
#define GLUE_TOWER_EFFECTIVE_TIME 2.5
#define GLUE_TOWER_UPGRADE_ADDED_EFFECTIVE_TIME 0.5
#define GLUE_TOWER_DAMAGE_RANGE 15
#define STANDARD_TOWER_RANGE 75
#define RUNNER_ENEMY "Icons/runner.png"
#define SCRAMBLER_ENEMY "Icons/scrambler.png"
#define SUPERTROOPER_ENEMY "Icons/supertrooper.png"
#define STUBBORNRUNNER_ENEMY "Icons/stubborn-runner.png"
#define RUNNER_INITIAL_HEALTH 250
#define RUNNER_SPEED 25
#define RUNNER_KILL_PRIZE 6
#define RUNNER_REACH_END_LOSS 1
#define STUBBORNRUNNER_INITIAL_HEALTH 400
#define STUBBORNRUNNER_SPEED 15
#define STUBBORNRUNNER_KILL_PRIZE 10
#define STUBBORNRUNNER_REACH_END_LOSS 4
#define SUPERTROOPER_INITIAL_HEALTH 500
#define SUPERTROOPER_SPEED 12.5
#define SUPERTROOPER_KILL_PRIZE 8
#define SUPERTROOPER_REACH_END_LOSS 4
#define SCRAMBLER_INITIAL_HEALTH 100
#define SCRAMBLER_SPEED 45
#define SCRAMBLER_KILL_PRIZE 4
#define SCRAMBLER_REACH_END_LOSS 2
#define RUNNER_TYPE "runner"
#define SCRAMBLER_TYPE "scrambler"
#define SUPERTROOPER_TYPE "supertrooper"
#define STUBBORNRUNNER_TYPE "stubbornrunner"
#define FIREBALL_PNG "Icons/fireball.png"
#define LIGHTNINGBALL_PNG "Icons/lightningball.png"
#define GLUEBALL_PNG "Icons/glueball.png"
#define MISSILE_SHOT_PNG "Icons/missileshot.png"
#define LIFE_BAR_IMG_PNG "Icons/lifebarimg.png"
#define YOU_WIN_PNG "Icons/youwin.png"
#define YOU_LOSE_PNG "Icons/youlose.png"
#define END_MESSAGE_WIDTH 550
#define END_MESSAGE_HIGHT 384
#define PROGRAM_SPEED 0.01
#define GATTLING_SOUND_EFFECT "SoundEffects/Gunfire.wav"
#define MISSILE_SOUND_EFFECT "SoundEffects/Missile.wav"
#define TESLA_SOUND_EFFECT "SoundEffects/Electriccurrent.wav"
#define PURCHASE_SOUND_EFFECT "SoundEffects/purchase.wav"
#define SELECT_SOUND_EFFECT "SoundEffects/select.wav"
#define WRONG_KEY_SOUND_EFFECT "SoundEffects/wrongkey.wav"
#define LOSE_SOUND_EFFECT "SoundEffects/lose.wav"
#define WIN_SOUND_EFFECT "SoundEffects/win.wav"
#define DIE_SOUND_EFFECT "SoundEffects/die.wav"

#endif